Regressão Linear: algoritmo de supervisão (conhecemos as variáveis)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [21]:
df=pd.read_csv('steel.csv')
display(df)

,Alloy code,C,Si,Mn,P,S,Ni,Cr,Mo,Cu,V,Al,N,Ceq,Nb + Ta,Temperature (°C),0.2% Proof Stress (MPa),Tensile Strength (MPa),Elongation (%),Reduction in Area (%)
0,MBB,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.610,0.04,0.000,0.003,0.0066,0.0,0.0000,27,342,490,30,71
1,MBB,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.610,0.04,0.000,0.003,0.0066,0.0,0.0000,100,338,454,27,72
2,MBB,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.610,0.04,0.000,0.003,0.0066,0.0,0.0000,200,337,465,23,69
3,MBB,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.610,0.04,0.000,0.003,0.0066,0.0,0.0000,300,346,495,21,70
4,MBB,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.610,0.04,0.000,0.003,0.0066,0.0,0.0000,400,316,489,26,79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
910,CCB,0.22,0.22,1.24,0.021,0.008,0.030,0.05,0.017,0.01,0.005,0.005,0.0116,0.0,0.0017,350,268,632,28,65
911,CCB,0.22,0.22,1.24,0.021,0.008,0.030,0.05,0.017,0.01,0.005,0.005,0.0116,0.0,0.0017,400,244,575,28,68
912,CCB,0.22,0.22,1.24,0.021,0.008,0.030,0.05,0.017,0.01,0.005,0.005,0.0116,0.0,0.0017,450,224,500,29,72
913,CCB,0.22,0.22,1.24,0.021,0.008,0.030,0.05,0.017,0.01,0.005,0.005,0.0116,0.0,0.0017,500,209,428,30,78
914,CCB,0.22,0.22,1.24,0.021,0.008,0.030,0.05,0.017,0.01,0.005,0.005,0.0116,0.0,0.0017,550,200,328,40,86

In [5]:
X=df.iloc[:,1:16]
X.head()

,C,Si,Mn,P,S,Ni,Cr,Mo,Cu,V,Al,N,Ceq,Nb + Ta,Temperature (°C)
0,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,27
1,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,100
2,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,200
3,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,300
4,0.12,0.36,0.52,0.009,0.003,0.089,0.97,0.61,0.04,0.0,0.003,0.0066,0.0,0.0,400

In [6]:
y=df.iloc[:, 17]
y.head()

0    490
1    454
2    465
3    495
4    489
Name:  Tensile Strength (MPa), dtype: int64

In [ ]:
#sns.heatmap(df.coor()) #mapa de correlação

In [10]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [18]:
y_pred=regressor.predict(X_test)
y_pred

array([357.64926167, 532.85787662, 349.9144921 , 449.64556369,
       328.11742751, 808.01804318, 371.81913418, 523.06147969,
       341.65011876, 387.42430523, 738.42853134, 410.96709229,
       496.48188803, 392.49992647, 653.84386721, 419.29527311,
       568.64011323, 316.92594108, 619.4165587 , 415.36837752,
       549.94851797, 517.33153821, 385.63110385, 447.66971683,
       406.01312246, 493.23969286, 415.42520758, 570.24252823,
       423.54368829, 425.42312237, 500.85645595, 415.30568586,
       601.0033993 , 557.81817049, 541.16168254, 533.35720706,
       506.48353145, 718.48132843, 322.43576235, 441.54425855,
       414.12560478, 522.3714284 , 560.96014436, 423.04045543,
       393.50862127, 536.98897749, 379.44632626, 352.49087773,
       410.2660759 , 436.3441764 , 426.62688261, 431.80455445,
       448.83284756, 458.96250669, 409.6240207 , 542.55566093,
       493.20138081, 566.30927715, 610.29918607, 364.03490397,
       735.00559016, 365.19847496, 503.81509679, 444.74678092,
       391.87113301, 631.29307008, 620.04613497, 549.60164136,
       663.01068787, 469.01725154, 820.03688839, 435.92266937,
       531.93503927, 533.75311157, 423.64024566, 385.72975872,
       379.35558716, 606.62179371, 688.26152542, 280.58934537,
       471.44262827, 711.77824227, 519.43353536, 557.28532735,
       363.83403926, 584.51180779, 563.17157452, 656.00095013,
       444.66372747, 547.40922596, 386.54915069, 513.602799  ,
       484.85018432, 422.86666288, 489.26374745, 475.39868363,
       328.18011917, 347.30129734, 470.00866983, 549.1552525 ,
       485.13838772, 762.13913885, 497.32354945, 685.46893853,
       397.95012938, 545.4265133 , 406.05143451, 510.22871378,
       448.42394719, 708.88947543, 581.90137493, 536.81639893,
       495.2378797 , 585.06365977, 568.25033272, 562.95874712,
       500.91808339, 555.62357706, 457.71973396, 349.02492131,
       389.70291843, 479.93830557, 713.53959647, 363.51935604,
       534.85797517, 469.50539319, 494.61642678, 681.97071977,
       544.85854428, 577.97447934, 553.67950756, 685.66758151,
       451.02229761, 611.84446189, 456.03655199, 427.8484991 ,
       647.74448954, 531.34786022, 345.98053913, 453.21814988,
       467.46668286, 724.32503467, 588.02922419, 454.3971275 ,
       479.51679855, 358.11550963, 363.93269413, 582.75720895,
       430.6932776 , 689.15595524, 558.37356772, 437.76313981,
       410.45554652, 669.08305393, 321.15795692, 494.70653724,
       689.98117768, 391.93276046, 571.07739746, 535.68207331,
       512.02944789, 582.42613805, 638.00478545, 393.96637809,
       384.23694682, 780.08063647, 388.21042528, 621.70121708,
       540.31292601, 566.65560886, 500.51068256, 361.11174607,
       474.18379789, 308.89674856, 881.64251982, 403.43080576,
       450.70761439, 492.08794414, 632.04680262, 750.86013229,
       655.37801166, 454.96586207, 542.21042131])

In [19]:
from sklearn.metrics import r2_score
eff=r2_score(y_test, y_pred)*100
eff

52.68901141308176

In [45]:
#para tratar a coluna que tiver nomes e não números
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder=LabelEncoder()
X[]=labelencoder.fit_transform(X[])
onehotencoder=OneHotEncoder(categorical_features=[n°coluna])
X=onehotencoder.fit_transform(X).toarray()

SyntaxError: invalid syntax (Temp/ipykernel_14272/411306689.py, line 5)

In [ ]:
#o processo anterior cria duas colunas, uma com o nome e outra com os valores correspondentes
X=X[:, 1:]